name: Android Build Check

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "package.json"
      - "yarn.lock"
jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Check
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: chmod +x gradlew && ./gradlew assembleDebug
